### ISSUE TITLE
Optionally use consult-fd instead of consult-find?

### ISSUE THREAD

**Issue by ktfleming** [karthink/consult-dir#32]
Consult has recently gained a [consult-fd](https://github.com/minad/consult/commit/5960ad787d8d1051d9c3140219d021496731e14c) command which uses the [fd](https://github.com/sharkdp/fd) utility to find files. In general it seems to be a replacement for `consult-find` with some benefits, one nice one being that it can automatically ignore files that are included in `.gitignore`.

What do you think about optionally allowing `consult-dir-jump-file` to use `consult-fd` instead of `consult-find`?

**Comment by karthink** [comment]
Thanks for bringing this up. `find` is almost guaranteed to be available whereas `fd` needs to be installed, so I'm not inclined to change the default.  I can't make it use `consult-fd` by default falling back on `consult-find`, since the arguments (provided after the `--` in consult commands) are different and it's not clear to the user what is being used.

I can make it a customization option though, something the user sets explicitly.

**Comment by karthink** [comment]
Added.
