### ISSUE TITLE
Error when using consult-dir before project.el is loaded

### ISSUE THREAD

**Issue by oantolin** [karthink/consult-dir#4]
You get the following error if you use `consult-dir` if you haven't yet loaded project or projectile:

```
Symbol’s value as variable is void: project--list
```

One simple way to fix it is to change `(when (eq project--list 'unset) ...)` to `(unless (boundp 'project--list) ...)`. (If you use `C-h v` on a `project--list` before loading project is does say it's value is `unset`, but that's not literally true.)

I'm not sure that really is the best way. For example, you could simple `(require 'project)`. Or you could define the project source in an `(with-eval-after-load 'project ...)`.

**Comment by karthink** [comment]
Fixed in e87362a8 (I think). I tweaked it so that `project--list` is set to `'unset` (like project.el does it.)

I was trying to minimize how much work `require` does on a library that's already loaded. This is probably unnecessary. Is it ok to have a `(require 'project)` in every invocation of `consultd-dir`?

**Comment by oantolin** [comment]
Sorry, I forgot to come back here and close the issue. That fix is fine.

By the way, somewhere else I had mentioned that it didn't quite seem to work on Windows, remember? It seems you need to escape the asterisks in `consult-find-args` (in particular, this has nothing to with `consult-dir`). With that everything works fine. I don't know why the escaping is needed and even think it might be a bug in Emacs on Windows.
